IBM-Blockchain/ansible-role-blockchain-platform-manager

meta/main.yml

Correct role name for Galaxy (resolves #2)

---

azure-pipelines.yml

Set up CI and automated publishing (resolves #10)

---

README.md

Update pre-reqs with Docker SDK for Python and sponge (resolves #9)

---

README.md

Add CI badge and Ansible Galaxy link (resolves #13)

---

tasks/manage-channel/create-channel.yml
tasks/manage-channel/update-channel.yml
tasks/manage-consortium.yml
templates/manage-channel/fabric-config-envelope.json.j2
templates/manage-consortium/fabric-config-envelope.json.j2

Always output files from configtxlator (resolves #20)

---

.vscode/extensions.json
.vscode/settings.json

Add extension recommendations and settings (resolves #22)

---

README.md

Add Example Playbook to README.md (resolves #25)

---

templates/manage-channel/fabric-channel-config-update.json.j2

Enable v1.4.2 channel capabilities (resolves #27)

---

README.md

Add jq to README.md, update other pre-reqs (resolves #32)

---

tasks/manage-channel.yml
tasks/manage-channel/join-channel-peer.yml
tasks/manage-channel/join-channel.yml
tasks/manage-channel/update-channel.yml
tasks/manage-consortium.yml
tasks/manage-contract/install-contract-peer.yml
tasks/manage-contract/instantiate-contract.yml
tasks/register-tls-user.yml
tasks/register-user.yml

Use changed_when: False for read-only commands (contributes to #34)

---

tasks/docker/create-peer.yml

Compare, then copy (if compare fails), then restart (if compare fails), otherwise do not restart.

Remove temporary Docker container for peer MSP/TLS (contributes to #34)

---

tasks/docker/create-orderer.yml

Compare, then copy (if compare fails), then restart (if compare fails), otherwise do not restart.

Remove temporary Docker container for orderer MSP/TLS and genesis block (contributes to #34)

---

tasks/main.yml

Temporary directory creation should not count as change (resolves #34)

---

azure-pipelines.yml
docker/.gitignore
docker/Dockerfile
docker/build.sh

Add Docker image and build scripts (contributes to #41)

---

README.md
tasks/software/create-ca.yml
tasks/software/create-msp.yml
tasks/software/create-orderer.yml
tasks/software/create-peer.yml
tasks/software/init.yml
templates/software/ca-node.json.j2
templates/software/create-ca.json.j2
templates/software/create-msp.json.j2
templates/software/create-orderer.json.j2
templates/software/create-peer.json.j2
templates/software/orderer-node.json.j2
templates/software/peer-node.json.j2

Add support for using IBM Blockchain Platform software (resolves #16)

---

README.md

Component ID names should be lower case (resolves #47)

---

docker/Dockerfile
tasks/docker/create-ca.yml
tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml

Upgrade to Fabric v1.4.4 (resolves #46)

---

README.md

This reverts commit 1d294cf0503edeef7a238d2f0cc17b126ca8c118.

Revert "Component ID names should be lower case (resolves #47)"

---

README.md

Add link to example playbook repository (resolves #53)

---

tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml
tasks/enroll-tls-user.yml
tasks/enroll-user.yml
tasks/register-tls-user.yml
tasks/register-user.yml

E305: use command instead of shell where possible (contributes to #15)

---

tasks/enroll-tls-user.yml
tasks/enroll-user.yml

E601: remove comparisions to literal True/False (contributes to #15)

---

tasks/docker/create-ca.yml
tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml
tasks/enroll-tls-user.yml
tasks/enroll-user.yml
tasks/manage-channel/create-channel.yml
tasks/manage-channel/update-channel.yml
tasks/manage-consortium.yml
tasks/register-tls-user.yml
tasks/register-user.yml
tasks/saas/create-ca.yml
tasks/saas/create-orderer.yml
tasks/saas/create-peer.yml
tasks/software/create-ca.yml
tasks/software/create-orderer.yml
tasks/software/create-peer.yml

E204: refactor lines to be less than 160 chars (contributes to #15)

---

tasks/manage-contract/instantiate-contract.yml
tasks/register-user.yml

E206: fix spacing around variable names (contributes to #15)

---

tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml
tasks/manage-channel/update-channel.yml
tasks/manage-consortium.yml

E306: set -o pipefail for all shells with pipes (contributes to #15)

---

.yamllint.yaml
azure-pipelines.yml
tasks/manage-consortium.yml

YAML_ERROR: add yamllint and fix error (contributes to #15)

---

README.md
meta/main.yml

Update description to match GitHub (resolves #65)

---

azure-pipelines.yml
meta/main.yml

Enable Lint errors in CI, fix last error (resolves #15)

---

README.md
azure-pipelines.yml
tasks/delete-gateway.yml
tasks/delete-msp.yml
tasks/delete-organisation.yml
tasks/docker/delete-ca.yml
tasks/docker/delete-msp.yml
tasks/docker/delete-orderer.yml
tasks/docker/delete-peer.yml
tasks/main.yml

Top level state variable (present/absent) for Docker (contributes to #43)

---

README.md
tasks/create-gateway.yml
tasks/create-organisation.yml
tests/test.yml

Add new gateways directory (resolves #31)

---

tasks/delete-organisation.yml

Delete gateways directory when state is absent (resolves #31)

---

defaults/main.yml

Default channels and contracts to empty array (resolves #75)

---

tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml

Fix restart checks for peers/orderers without TLS (resolves #77)

---

README.md
tasks/docker/create-ca.yml
tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml

Add top-level Docker labels for containers/volumes (resolves #79)

---

docker/Dockerfile

Add bash to Docker image (resolves #83)

---

README.md
tasks/docker/create-peer.yml

Set CORE_PEER_NETWORKID if supplied (resolves #87)

---

README.md
defaults/main.yml
tasks/create-gateway.yml
tasks/create-organisation.yml
tasks/delete-gateway.yml
tasks/delete-organisation.yml
tasks/main.yml
templates/gateway.json.j2
tests/test.yml

Separate gateway configuration and allow specification of names/peers (resolves #85)

---

tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml
tasks/enroll-tls-user.yml
tasks/enroll-user.yml
tasks/manage-channel.yml
tasks/manage-channel/create-channel.yml
tasks/manage-channel/join-channel.yml
tasks/manage-channel/update-channel.yml
tasks/manage-consortium.yml
tasks/manage-contract/install-contract-peer.yml
tasks/manage-contract/instantiate-contract.yml
tasks/register-tls-user.yml
tasks/register-user.yml

Quote all path references in commands (resolves #90)

---

tasks/docker/delete-peer.yml

Delete peer data volume when state set to absent (resolves #97)

---

azure-pipelines.yml

Remove restrictive AZP trigger configuration (resolves #92)

---

azure-pipelines.yml

Download Fabric CLI from GitHub in AZP (resolves #101)

---

docker/Dockerfile

Update Alpine Linux to 3.11 and Docker to 19.03.5 (resolves #103)

---

templates/manage-channel/fabric-channel-config-update.json.j2
templates/manage-channel/fabric-policies.json.j2

Readers/Writers mod_policy should be Admins (resolves #105)

---

tests/.gitignore

Add .gitignore file for tests directory (resolves #107)

---

azure-pipelines.yml

Explicitly trigger AZP build on tags (resolves #92)

---

README.md
tasks/docker/create-ca.yml
tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml
tests/test.yml

Add Docker hostname configuration (resolves #111)

---

tasks/docker/create-ca.yml
tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml
templates/docker/configtx.yaml.j2

Docker hostnames not resolvable, TLS certificates wrong (resolves #111)

---

tasks/docker/create-peer.yml

Peer data volume creation has wrong volume name (resolves #114)

---

azure-pipelines.yml

Publish ibmblockchain/vscode-prereqs image (resolves #41)

---

tasks/saas/create-ca.yml
tasks/saas/create-msp.yml
tasks/saas/create-orderer.yml
tasks/saas/create-peer.yml

Find components by display name in SaaS (contributes to #118)

---

tasks/saas/delete-ca.yml
tasks/saas/delete-msp.yml
tasks/saas/delete-orderer.yml
tasks/saas/delete-peer.yml

Delete components in SaaS when state set to absent (contributes to #120)

---

tasks/saas/create-orderer.yml
tasks/software/create-ca.yml
tasks/software/create-msp.yml
tasks/software/create-orderer.yml
tasks/software/create-peer.yml

Find components by display name in software (resolves #118)

---

tasks/software/delete-ca.yml
tasks/software/delete-msp.yml
tasks/software/delete-orderer.yml
tasks/software/delete-peer.yml

Delete components in software when state set to absent (resolves #120)

---

tasks/saas/create-ca.yml
tasks/saas/create-msp.yml
tasks/saas/create-orderer.yml
tasks/saas/create-peer.yml
tasks/software/create-ca.yml
tasks/software/create-msp.yml
tasks/software/create-orderer.yml
tasks/software/create-peer.yml

Flag creation of SaaS/software components as a change (resolves #124)

---

tasks/saas/delete-ca.yml
tasks/saas/delete-orderer.yml
tasks/saas/delete-peer.yml
tasks/software/delete-ca.yml
tasks/software/delete-orderer.yml
tasks/software/delete-peer.yml

Signed-off-by: rthatcher <robert.thatcher@uk.ibm.com>

Delete Tasks modified to delete kubernetes elements. Issue 134

---

tasks/saas/create-ca.yml
tasks/saas/create-orderer.yml
tasks/saas/create-peer.yml
tasks/software/create-ca.yml
tasks/software/create-orderer.yml
tasks/software/create-peer.yml

Bump SaaS/software timeouts to 10 minutes (resolves #129)

---

tasks/saas/create-ca.yml
tasks/saas/create-msp.yml
tasks/saas/create-orderer.yml
tasks/saas/create-peer.yml
tasks/saas/delete-ca.yml
tasks/saas/delete-msp.yml
tasks/saas/delete-orderer.yml
tasks/saas/delete-peer.yml
tasks/software/create-ca.yml
tasks/software/create-msp.yml
tasks/software/create-orderer.yml
tasks/software/create-peer.yml
tasks/software/delete-ca.yml
tasks/software/delete-msp.yml
tasks/software/delete-orderer.yml
tasks/software/delete-peer.yml

Add skip_cache=yes to all IBP HTTP GET requests (resolves #139)

---

templates/saas/ca-node.json.j2
templates/saas/orderer-node.json.j2
templates/saas/peer-node.json.j2
templates/software/ca-node.json.j2
templates/software/orderer-node.json.j2
templates/software/peer-node.json.j2

Add wallet/identity properties to IBP SaaS/software node files (resolves #141)

---

README.md
tasks/manage-consortium.yml
templates/manage-consortium/fabric-orderer-values.json.j2

Allow block cutting configuration for orderer (resolves #93)

---

azure-pipelines.yml
docker/Dockerfile
files/sampleconfig/core.yaml
tasks/manage-channel.yml
tasks/manage-channel/create-channel.yml
tasks/manage-channel/join-channel-peer.yml
tasks/manage-channel/join-channel.yml
tasks/manage-channel/update-channel.yml
tasks/manage-consortium.yml
tasks/manage-contract/install-contract-peer.yml
tasks/manage-contract/instantiate-contract.yml

Provide FABRIC_CFG_PATH in env for all peer commands (resolves #80)

---

README.md
tasks/manage-contract/instantiate-contract.yml

Add collections config file option to smart contract (resolves #127)

---

azure-pipelines.yml
docker/Dockerfile
tasks/docker/create-ca.yml
tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml

Upgrade to Fabric v1.4.6 (resolves #148)

---

README.md
templates/docker/ca-node.json.j2
templates/docker/orderer-node.json.j2
templates/docker/peer-node.json.j2
templates/gateway.json.j2

Small additions to Ansible
-  Added new option to generate gateway and node information suitable for Docker networking
-  Added implementation for the same
-  Updated READ.me instructions

Docker networking option

---

README.md

Update readme Playbook Example to use v2 format
Signed-off-by: lmuswere <lynn14m@gmail.com>

Update readme for v2 format

---

azure-pipelines.yml
docker/Dockerfile
tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml

Signed-off-by: lmuswere <lynn14m@gmail.com>

Upgrade to Fabric v2.1.0

---

tasks/manage-channel/update-channel.yml
tasks/manage-consortium.yml

Signed-off-by: lesleyannj <lesleyannj@hotmail.com>

[164] Allow hyphen in MSP name

---

README.md

Add a big warning message and redirect to the collection

---

azure-pipelines.yml
docker/Dockerfile
tasks/docker/create-orderer.yml
tasks/docker/create-peer.yml

Closes #167 
Signed-off-by: Leonor Quintais <lquintai@uk.ibm.com>

[issue-94-branch] - update fabric version to LTS 2.2.0.

---

azure-pipelines.yml
docker/Dockerfile
tasks/docker/create-ca.yml

Signed-off-by: Leonor Quintais <lquintai@uk.ibm.com>

[issue-94-branch] - update fabric ca version to 1.4.7.
